package Hibernate;
// Generated 12-may-2015 11:43:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private String dni;
     private String nombreYapellidos;
     private String fechaNacimiento;
     private Integer telefono;
     private String email;
     private String puesto;
     private Set facturases = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(String dni, String nombreYapellidos) {
        this.dni = dni;
        this.nombreYapellidos = nombreYapellidos;
    }
    public Empleados(String dni, String nombreYapellidos, String fechaNacimiento, Integer telefono, String email, String puesto, Set facturases) {
       this.dni = dni;
       this.nombreYapellidos = nombreYapellidos;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.email = email;
       this.puesto = puesto;
       this.facturases = facturases;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombreYapellidos() {
        return this.nombreYapellidos;
    }
    
    public void setNombreYapellidos(String nombreYapellidos) {
        this.nombreYapellidos = nombreYapellidos;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


