package Hibernate;
// Generated 12-may-2015 11:43:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Fabricantes generated by hbm2java
 */
public class Fabricantes  implements java.io.Serializable {


     private String denominacion;
     private String localizacion;
     private String web;
     private String email;
     private Set productoses = new HashSet(0);

    public Fabricantes() {
    }

	
    public Fabricantes(String denominacion) {
        this.denominacion = denominacion;
    }
    public Fabricantes(String denominacion, String localizacion, String web, String email, Set productoses) {
       this.denominacion = denominacion;
       this.localizacion = localizacion;
       this.web = web;
       this.email = email;
       this.productoses = productoses;
    }
   
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


