package Hibernate;
// Generated 12-may-2015 11:43:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer codigo;
     private Fabricantes fabricantes;
     private String nombre;
     private String categoria;
     private Integer edad;
     private String procedencia;
     private Double precio;
     private Set productosfacturases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String nombre) {
        this.nombre = nombre;
    }
    public Productos(Fabricantes fabricantes, String nombre, String categoria, Integer edad, String procedencia, Double precio, Set productosfacturases) {
       this.fabricantes = fabricantes;
       this.nombre = nombre;
       this.categoria = categoria;
       this.edad = edad;
       this.procedencia = procedencia;
       this.precio = precio;
       this.productosfacturases = productosfacturases;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }
    
    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getProductosfacturases() {
        return this.productosfacturases;
    }
    
    public void setProductosfacturases(Set productosfacturases) {
        this.productosfacturases = productosfacturases;
    }




}


