package Hibernate;
// Generated 12-may-2015 11:43:36 by Hibernate Tools 3.6.0



/**
 * Productosfacturas generated by hbm2java
 */
public class Productosfacturas  implements java.io.Serializable {


     private Integer codigoTabla;
     private Facturas facturas;
     private Productos productos;

    public Productosfacturas() {
    }

    public Productosfacturas(Facturas facturas, Productos productos) {
       this.facturas = facturas;
       this.productos = productos;
    }
   
    public Integer getCodigoTabla() {
        return this.codigoTabla;
    }
    
    public void setCodigoTabla(Integer codigoTabla) {
        this.codigoTabla = codigoTabla;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


